### PR TITLE
Restructure README sections

### PR DESCRIPTION
**Pull request by davidak**
- Change logo to a smaller one without margin
- Remove "Current Version" from description. it's visible as badges now
- Add "Table of Contents" section
- Move content of Development section to Contributing
- Add Support, Maintainer, Contributing and License section
- also small improvements in the text

Most of the text still needs improvement. This is a task for another PR.

Please provide feedback and suggest better writing style for the new text. My goal is to have a short, to the point description in a welcoming way, so users are encouraged to become contributors.

Preview: [rendered view](https://github.com/greenbone/gvm-tools/blob/3a052570f8a6f6cf991f5ed340df440702ca146c/README.md)

### CODE REVIEW

**Comment by bjoernricks** [comment]
Would be nice to change the requirements to a markdown list too

**Comment by bjoernricks** [comment]
personally i would change all shell commands to start with

```
$ command-to-run-in-shell
```

**Comment by davidak** [comment]
>Would be nice to change the requirements to a markdown list too

I havn't touched that part yet. Will do later.

>personally i would change all shell commands to start with `$`

have you any reference that this is a suggested and common practice? A point against it would be that it's harder to copy. a point for it is that you can distinguish between command and output.

Example with https://github.com/onyxfish/command-line-tutorial#whats-in-there
and without https://docs.gitlab.com/ee/gitlab-basics/command-line-commands.html#list-what-s-in-the-current-directory

But again, it's not in the scope of this PR. It's just about sections (and some minor improvements).

**Comment by bjoernricks** [comment]
> have you any reference that this is a suggested and common practice? A point against it would be that it's harder to copy. a point for it is that you can distinguish between command and output.
> 
> Example with https://github.com/onyxfish/command-line-tutorial#whats-in-there
> and without https://docs.gitlab.com/ee/gitlab-basics/command-line-commands.html#list-what-s-in-the-current-directory
> 
> But again, it's not in the scope of this PR. It's just about sections (and some minor improvements).

E.g. https://github.com/pypa/pipenv is using the $ notation and https://github.com/facebook/create-react-app isn't. You are right it's easier to copy&paste without the $ and therefore we should keep it as it is.

**Comment by davidak** [comment]
I did some research and think this is a sane convention: https://meta.askubuntu.com/a/14933/498844

**Comment by davidak** [comment]
I'm now using the new logo and merged master back. Ready to merge from my side.

Please review again.

**Pull request merged**
