### PR TITLE
Replace pipenv with poetry

### PR DESCRIPTION
**Pull request by bjoernricks**
**Checklist**:

- [n/a] Tests
- [x] [CHANGELOG](https://github.com/greenbone/gvm-tools/blob/master/CHANGELOG.md) Entry
- [x] Documentation

### CODE REVIEW

**Comment by wiegandm** [comment]
First impressions:
- Setting up and using a `venv` with `poetry` seems to work.
- Setting up the `venv` takes considerably longer than `pipenv`. But this is likely due to `pipenv`s arguably messy collection of vendored and pseudo-vendored dependencies, so no obstacle to `poetry` in my opinion.
- Using `poetry install` will also install the `gvm-tools` package from the local directory into the `venv`, while `pipenv install --dev` only installed the *dependencies* and left the user to call `pip install .` or similar inside the `venv`. I have no general objection to this if it is indeed intentional, but this should be made clearer in the documentation.

**Comment by wiegandm** [comment]
> Using `poetry install` will also install the gvm-tools package from the local directory into the venv, while `pipenv install --dev` only installed the dependencies 

After reading https://python-poetry.org/docs/cli/#install, I understand that this is the default behavior of `poetry`: 

> By default `poetry` will install your project's package everytime you run `install` (..) If you want to skip this installation, use the `--no-root` option.

So this actually sounds sensible and easier to use -- but I would still suggest noting this change of behavior in the documentation/changelog.

**Comment by bjoernricks** [comment]
Yes `poetry install` is different to `pipenv install`

* It installs dev packages by default
* It installs also the own package in editable mode

Personally I think both are a good think. It is much easier that the provided scripts of the python package get installed by default then to run `pipenv run pip install -e .`

**Comment by bjoernricks** [comment]
I've extended the changelog entry accordingly.

**Comment by wiegandm** [comment]
There is still a last reference to `pipenv` in `RELEASE.md`, perhaps this could be replaced by simply creating a `venv` with `python3 -m venv gvm-tools-install-test`, activating it and testing the install from `test.pypi.org` there?

**Pull request merged**
