### PR TITLE
Update for update-task-target.gmp

### PR DESCRIPTION
**Pull request by jschwartz27**

### CODE REVIEW

**Comment by jschwartz27** [comment]
Sorry about the late response. The reason the code doesn't notify the user
is because the function is merely attempting to delete the old target, but
if it is attached to another task it will fail to be deleted. So if this
happens there actually isn't a problem, it is just that the target won't be
deleted. The reason to delete the target in the first place is in the case
that it is only being used by the current task, it won't be left existing
after the new target has been created and attached to the task. I hope this
clarifies the matter, but please let me know if something else should be
done. :)

Best,
Joshua

**Comment by swaterkamp** [comment]
I don't feel like using errors as functional logic is a good thing. Shouldn't you rather check, if the target is used by the current task only or for others as well and then act accordingly? And not just try to delete it in any case and ignore failure?

**Comment by jschwartz27** [comment]
That is a fair point, I will change it to function like you suggested!

**Comment by bjoernricks** [comment]
IMHO this got handled in #129 too

**Pull request closed without merging**
